name: aria2c
base: core18
version: 1.35.0
summary: The next generation download utility
description: |
  Aria2 is a lightweight multi-protocol & multi-source command-line download utility. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink. aria2 can be manipulated via built-in JSON-RPC and XML-RPC interfaces.

grade: stable
confinement: strict

parts:
  aria2:
    # plugin: autotools
    # configflags:
    #   - --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt
    #   - ARIA2_STATIC=yes
    # source-type: tar
    # source: https://github.com/aria2/aria2/releases/download/release-$SNAPCRAFT_PROJECT_VERSION/aria2-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    # build-packages:
    #   - g++
    #   - libssl-dev
    plugin: dump
    source: aria2/aria2.tar.gz
    stage-packages:
      - libicu60
      - libxml2

apps:
  aria2c:
    command: aria2c
