name: Build
on:
  push:
    branches: [ feature/gh-action ]
#   schedule:
#     # run every day at midnight
#     - cron:  '0 0 * * *'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        ./configure --with-ca-bundle='/etc/ssl/certs/ca-certificates.crt'
        make
        tar -czvf aria2.tar.gz src/aria2c
        ls -l aria2.tar.gz